TWITCH_APP_ID='YOUR TWITCH APP ID HERE'
TWITCH_APP_SECRET='YOUR TWITCH APP SECRET HERE'
TWITCH_USERNAME='YOUR TWITCH USERNAME HERE'
TESSERACT_PATH=r'YOUR TESSERACT PATH HERE'
DEBUG_SAVE_IMAGES = False
TWITCH_VIDEO_CAPTURE_QUALITY = 'best'
